import { GenderEnum, LevelEnum, SourceEnum } from "@/types/entities.types";
import type { Client } from "../types/clients.types";

export const CLIENTS_CONSTANTS = {
  PAGE_TITLE: "Gestión de clientes",
  PAGE_SUBTITLE: "Gestión de clientes y su información relacionada",
  CREATE_LABEL: "Crear Cliente",
  EDIT_LABEL: "Editar Cliente",
  DELETE_LABEL: "Eliminar Cliente",
};

export const CLIENT_LEVEL_LABELS: Record<Client["level"], string> = {
  bronze: "Bronce",
  silver: "Plata",
  gold: "Oro",
  platinum: "Platino",
};

export const CLIENT_LEVEL_COLORS: Record<Client["level"], string> = {
  bronze: "#cd7f32",
  silver: "#c0c0c0",
  gold: "#ffd700",
  platinum: "#e5e4e2",
};

export const CLIENT_SOURCE_LABELS: Record<Client["source"], string> = {
  in_store: "En tienda",
  web: "Página Web",
  whatsapp: "WhatsApp",
  manual: "Manual",
};

export const CLIENT_SOURCE_COLORS: Record<
  Client["source"],
  "default" | "primary" | "secondary" | "success" | "warning" | "info" | "error"
> = {
  in_store: "primary",
  web: "info",
  whatsapp: "success",
  manual: "default",
};

export const CLIENT_FORM_TITLES = {
  CONTACT_DATA: "Datos de contacto",
  FIDELIZATION_DATA: "Datos de fidelización",
  UBICATION_DATA: "Datos de ubicación",
};

export const DEFAULT_CLIENT_FORM_VALUES: Client = {
  address: "",
  city: "",
  country: "Argentina",
  email: "",
  fullName: "",
  phone: "",
  province: "",
  points: 0,
  source: SourceEnum.Web,
};

export const mockClients: Client[] = [
  {
    id: "clt_001",
    fullName: "Juan Pérez",
    email: "juan.perez@example.com",
    phone: "+5491123456789",
    address: "Av. Corrientes 1234",
    city: "CABA",
    province: "Buenos Aires",
    country: "Argentina",
    birthday: "1990-03-15",
    gender: GenderEnum.Male,
    createdAt: "2024-06-01T12:00:00Z",
    updatedAt: "2024-06-20T15:00:00Z",
    points: 150,
    level: LevelEnum.Silver,
    source: SourceEnum.InStore,
    notes: "Cliente frecuente",
    tags: ["VIP", "fútbol"],
    isActive: true,
    tenantId: "tenant_01",
  },
  {
    id: "clt_002",
    fullName: "María Gómez",
    email: "maria.gomez@example.com",
    phone: "+5491156784321",
    address: "Calle Falsa 123",
    city: "Rosario",
    province: "Santa Fe",
    country: "Argentina",
    birthday: "1985-12-22",
    gender: GenderEnum.Female,
    createdAt: "2024-05-15T10:30:00Z",
    updatedAt: "2024-06-22T14:20:00Z",
    points: 320,
    level: LevelEnum.Gold,
    source: SourceEnum.Web,
    tags: ["cumpleañera"],
    isActive: true,
    tenantId: "tenant_01",
  },
  {
    id: "clt_003",
    fullName: "Alex Silva",
    email: "alex.silva@example.com",
    phone: "+5491166667777",
    address: "Ruta 8 km 45",
    city: "Pilar",
    province: "Buenos Aires",
    country: "Argentina",
    createdAt: "2024-01-10T11:00:00Z",
    updatedAt: "2024-05-30T11:30:00Z",
    points: 80,
    level: LevelEnum.Bronze,
    source: SourceEnum.Manual,
    isActive: false,
    tenantId: "tenant_02",
  },
  {
    id: "clt_004",
    fullName: "Lucía Martínez",
    email: "lucia.m@example.com",
    phone: "+5491177778888",
    address: "Bv. Oroño 501",
    city: "Rosario",
    province: "Santa Fe",
    country: "Argentina",
    birthday: "1999-09-09",
    gender: GenderEnum.Female,
    createdAt: "2024-04-01T08:20:00Z",
    updatedAt: "2024-06-10T18:45:00Z",
    points: 210,
    level: LevelEnum.Silver,
    source: SourceEnum.WhatsApp,
    tags: ["vegan"],
    isActive: true,
    tenantId: "tenant_01",
  },
  {
    id: "clt_005",
    fullName: "Carlos Ruiz",
    email: "carlos.ruiz@example.com",
    phone: "+5491133334444",
    address: "Av. San Martín 900",
    city: "Mendoza",
    province: "Mendoza",
    country: "Argentina",
    createdAt: "2023-12-12T10:10:00Z",
    updatedAt: "2024-06-01T09:00:00Z",
    points: 45,
    level: LevelEnum.Bronze,
    source: SourceEnum.InStore,
    isActive: true,
    tenantId: "tenant_03",
  },
  {
    id: "clt_006",
    fullName: "Emma López",
    email: "emma.lopez@example.com",
    phone: "+5491199990000",
    address: "Diagonal Norte 350",
    city: "La Plata",
    province: "Buenos Aires",
    country: "Argentina",
    birthday: "2001-07-07",
    gender: GenderEnum.Female,
    createdAt: "2024-02-20T14:40:00Z",
    updatedAt: "2024-06-21T13:10:00Z",
    points: 500,
    level: LevelEnum.Platinum,
    source: SourceEnum.Web,
    tags: ["celíaca"],
    isActive: true,
    tenantId: "tenant_01",
  },
  {
    id: "clt_007",
    fullName: "Diego Torres",
    email: "diego.torres@example.com",
    phone: "+5491144445555",
    address: "Av. Libertador 1800",
    city: "CABA",
    province: "Buenos Aires",
    country: "Argentina",
    createdAt: "2024-06-10T15:00:00Z",
    updatedAt: "2024-06-10T15:00:00Z",
    points: 120,
    level: LevelEnum.Silver,
    source: SourceEnum.Web,
    isActive: true,
    tenantId: "tenant_02",
  },
  {
    id: "clt_008",
    fullName: "Sofía Herrera",
    email: "sofia.herrera@example.com",
    phone: "+5491167891234",
    address: "Los Álamos 123",
    city: "Córdoba",
    province: "Córdoba",
    country: "Argentina",
    createdAt: "2024-06-01T17:30:00Z",
    updatedAt: "2024-06-19T11:00:00Z",
    points: 90,
    level: LevelEnum.Bronze,
    source: SourceEnum.WhatsApp,
    isActive: true,
    tenantId: "tenant_01",
  },
  {
    id: "clt_009",
    fullName: "Martín Castro",
    email: "martin.castro@example.com",
    phone: "+5491134567890",
    address: "Mitre 400",
    city: "Tucumán",
    province: "Tucumán",
    country: "Argentina",
    createdAt: "2024-05-10T09:30:00Z",
    updatedAt: "2024-06-15T12:15:00Z",
    points: 260,
    level: LevelEnum.Gold,
    source: SourceEnum.Manual,
    isActive: true,
    tenantId: "tenant_03",
  },
];
